package com.thinkgem.jeesite.modules.project.entity;
import java.io.Serializable;
import java.sql.Blob;
import java.util.Date;

/**
 * Model class of 专家附件.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProjectAttach implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 附件ID. */
	private String id;

	/** 项目信息表. */
	private ProjectInfo prjProjectInfo;

	/** 附件名称. */
	private String attachName;

	/** 附件类型. */
	private String attachType;

	/** 附件位置. */
	private String attachLink;

	/** 附件存储. */
	private Blob attachStore;

	/** 创建者. */
	private String createBy;

	/** 创建时间. */
	private Date createDate;

	/** 更新者. */
	private String updateBy;

	/** 更新时间. */
	private Date updateDate;

	/** 备注信息. */
	private String remarks;

	/** 删除标记. */
	private String delFlag;

	/**
	 * Constructor.
	 */
	public ProjectAttach() {
	}

	/**
	 * Set the 附件ID.
	 * 
	 * @param id
	 *            附件ID
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the 附件ID.
	 * 
	 * @return 附件ID
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 项目信息表.
	 * 
	 * @param prjProjectInfo
	 *            项目信息表
	 */
	public void setPrjProjectInfo(ProjectInfo prjProjectInfo) {
		this.prjProjectInfo = prjProjectInfo;
	}

	/**
	 * Get the 项目信息表.
	 * 
	 * @return 项目信息表
	 */
	public ProjectInfo getPrjProjectInfo() {
		return this.prjProjectInfo;
	}

	/**
	 * Set the 附件名称.
	 * 
	 * @param attachName
	 *            附件名称
	 */
	public void setAttachName(String attachName) {
		this.attachName = attachName;
	}

	/**
	 * Get the 附件名称.
	 * 
	 * @return 附件名称
	 */
	public String getAttachName() {
		return this.attachName;
	}

	/**
	 * Set the 附件类型.
	 * 
	 * @param attachType
	 *            附件类型
	 */
	public void setAttachType(String attachType) {
		this.attachType = attachType;
	}

	/**
	 * Get the 附件类型.
	 * 
	 * @return 附件类型
	 */
	public String getAttachType() {
		return this.attachType;
	}

	/**
	 * Set the 附件位置.
	 * 
	 * @param attachLink
	 *            附件位置
	 */
	public void setAttachLink(String attachLink) {
		this.attachLink = attachLink;
	}

	/**
	 * Get the 附件位置.
	 * 
	 * @return 附件位置
	 */
	public String getAttachLink() {
		return this.attachLink;
	}

	/**
	 * Set the 附件存储.
	 * 
	 * @param attachStore
	 *            附件存储
	 */
	public void setAttachStore(Blob attachStore) {
		this.attachStore = attachStore;
	}

	/**
	 * Get the 附件存储.
	 * 
	 * @return 附件存储
	 */
	public Blob getAttachStore() {
		return this.attachStore;
	}

	/**
	 * Set the 创建者.
	 * 
	 * @param createBy
	 *            创建者
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * Get the 创建者.
	 * 
	 * @return 创建者
	 */
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createDate
	 *            创建时间
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * Set the 更新者.
	 * 
	 * @param updateBy
	 *            更新者
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * Get the 更新者.
	 * 
	 * @return 更新者
	 */
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updateDate
	 *            更新时间
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * Set the 备注信息.
	 * 
	 * @param remarks
	 *            备注信息
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the 备注信息.
	 * 
	 * @return 备注信息
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the 删除标记.
	 * 
	 * @param delFlag
	 *            删除标记
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the 删除标记.
	 * 
	 * @return 删除标记
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ProjectAttach other = (ProjectAttach) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
