package com.thinkgem.jeesite.modules.expmanage.entity;

import java.io.Serializable;

/**
 * Model class of 委员会专家（评委）表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CommitteeExpert implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 评委会信息表. */
	private CommitteeInfo comitteeCommitteeInfo;

	/** 专家确认表. */
	private ExpertConfirm expertExpertConfirm;

	/** 专家担任评委的类别. */
	private String raterType;

	/**
	 * Constructor.
	 */
	public CommitteeExpert() {
	}

	/**
	 * Set the 评委会信息表.
	 * 
	 * @param comitteeCommitteeInfo
	 *            评委会信息表
	 */
	public void setComitteeCommitteeInfo(CommitteeInfo comitteeCommitteeInfo) {
		this.comitteeCommitteeInfo = comitteeCommitteeInfo;
	}

	/**
	 * Get the 评委会信息表.
	 * 
	 * @return 评委会信息表
	 */
	public CommitteeInfo getComitteeCommitteeInfo() {
		return this.comitteeCommitteeInfo;
	}

	/**
	 * Set the 专家确认表.
	 * 
	 * @param expertExpertConfirm
	 *            专家确认表
	 */
	public void setExpertExpertConfirm(ExpertConfirm expertExpertConfirm) {
		this.expertExpertConfirm = expertExpertConfirm;
	}

	/**
	 * Get the 专家确认表.
	 * 
	 * @return 专家确认表
	 */
	public ExpertConfirm getExpertExpertConfirm() {
		return this.expertExpertConfirm;
	}

	/**
	 * Set the 专家担任评委的类别.
	 * 
	 * @param raterType
	 *            专家担任评委的类别
	 */
	public void setRaterType(String raterType) {
		this.raterType = raterType;
	}

	/**
	 * Get the 专家担任评委的类别.
	 * 
	 * @return 专家担任评委的类别
	 */
	public String getRaterType() {
		return this.raterType;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((comitteeCommitteeInfo == null) ? 0 : comitteeCommitteeInfo.hashCode());
		result = prime * result + ((expertExpertConfirm == null) ? 0 : expertExpertConfirm.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CommitteeExpert other = (CommitteeExpert) obj;
		if (comitteeCommitteeInfo == null) {
			if (other.comitteeCommitteeInfo != null) {
				return false;
			}
		} else if (!comitteeCommitteeInfo.equals(other.comitteeCommitteeInfo)) {
			return false;
		}
		if (expertExpertConfirm == null) {
			if (other.expertExpertConfirm != null) {
				return false;
			}
		} else if (!expertExpertConfirm.equals(other.expertExpertConfirm)) {
			return false;
		}
		return true;
	}

}
