package com.thinkgem.jeesite.modules.expmanage.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 专家请假表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ExpertLeave implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 专家请假ID. */
	private String id;

	/** 专家确认表. */
	private ExpertConfirm expertExpertConfirm;

	/** 请假事项原因. */
	private String reason;

	/** 请假开始时间. */
	private Date leaveStart;

	/** 请假结束时间. */
	private Date leaveEnd;

	/** 请假获批标志. */
	private String leaveConfirm;

	/** 创建者. */
	private String createBy;

	/** 创建时间. */
	private Date createDate;

	/** 更新者. */
	private String updateBy;

	/** 更新时间. */
	private Date updateDate;

	/** 备注信息. */
	private String remarks;

	/** 删除标记. */
	private String delFlag;

	/**
	 * Constructor.
	 */
	public ExpertLeave() {
	}

	/**
	 * Set the 专家请假ID.
	 * 
	 * @param id
	 *            专家请假ID
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the 专家请假ID.
	 * 
	 * @return 专家请假ID
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 专家确认表.
	 * 
	 * @param expertExpertConfirm
	 *            专家确认表
	 */
	public void setExpertExpertConfirm(ExpertConfirm expertExpertConfirm) {
		this.expertExpertConfirm = expertExpertConfirm;
	}

	/**
	 * Get the 专家确认表.
	 * 
	 * @return 专家确认表
	 */
	public ExpertConfirm getExpertExpertConfirm() {
		return this.expertExpertConfirm;
	}

	/**
	 * Set the 请假事项原因.
	 * 
	 * @param reason
	 *            请假事项原因
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}

	/**
	 * Get the 请假事项原因.
	 * 
	 * @return 请假事项原因
	 */
	public String getReason() {
		return this.reason;
	}

	/**
	 * Set the 请假开始时间.
	 * 
	 * @param leaveStart
	 *            请假开始时间
	 */
	public void setLeaveStart(Date leaveStart) {
		this.leaveStart = leaveStart;
	}

	/**
	 * Get the 请假开始时间.
	 * 
	 * @return 请假开始时间
	 */
	public Date getLeaveStart() {
		return this.leaveStart;
	}

	/**
	 * Set the 请假结束时间.
	 * 
	 * @param leaveEnd
	 *            请假结束时间
	 */
	public void setLeaveEnd(Date leaveEnd) {
		this.leaveEnd = leaveEnd;
	}

	/**
	 * Get the 请假结束时间.
	 * 
	 * @return 请假结束时间
	 */
	public Date getLeaveEnd() {
		return this.leaveEnd;
	}

	/**
	 * Set the 请假获批标志.
	 * 
	 * @param leaveConfirm
	 *            请假获批标志
	 */
	public void setLeaveConfirm(String leaveConfirm) {
		this.leaveConfirm = leaveConfirm;
	}

	/**
	 * Get the 请假获批标志.
	 * 
	 * @return 请假获批标志
	 */
	public String getLeaveConfirm() {
		return this.leaveConfirm;
	}

	/**
	 * Set the 创建者.
	 * 
	 * @param createBy
	 *            创建者
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * Get the 创建者.
	 * 
	 * @return 创建者
	 */
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createDate
	 *            创建时间
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * Set the 更新者.
	 * 
	 * @param updateBy
	 *            更新者
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * Get the 更新者.
	 * 
	 * @return 更新者
	 */
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updateDate
	 *            更新时间
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * Set the 备注信息.
	 * 
	 * @param remarks
	 *            备注信息
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the 备注信息.
	 * 
	 * @return 备注信息
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the 删除标记.
	 * 
	 * @param delFlag
	 *            删除标记
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the 删除标记.
	 * 
	 * @return 删除标记
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ExpertLeave other = (ExpertLeave) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
