package com.freebirdweij.cloudroom.modules.project.entity;
import java.io.Serializable;
import java.util.Date;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.freebirdweij.cloudroom.modules.expmanage.entity.ExpertConfirm;


/**
 * Model class of 项目专家表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProjectExpert implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 项目信息表. */
	private ProjectInfo prjProjectInfo;

	/** 专家确认表. */
	private ExpertConfirm expertExpertConfirm;

	/** 第几次抽取. */
	private Integer fetchTime;

	/** 抽取有效标志. */
	private String fetchStatus;

	/** 执行评审开始时间. */
	private Date reviewBegin;

	/** 执行评审结束时间. */
	private Date reviewEnd;

	/** 专家接受任务标志。. */
	private String expertAccept;

	/** 创建者. */
	private String createBy;

	/** 创建时间. */
	private Date createDate;

	/** 更新者. */
	private String updateBy;

	/** 更新时间. */
	private Date updateDate;

	/** 备注信息. */
	private String remarks;

	/** 删除标记. */
	private String delFlag;

	/**
	 * Constructor.
	 */
	public ProjectExpert() {
	}

	/**
	 * Set the 项目信息表.
	 * 
	 * @param prjProjectInfo
	 *            项目信息表
	 */
	public void setPrjProjectInfo(ProjectInfo prjProjectInfo) {
		this.prjProjectInfo = prjProjectInfo;
	}

	/**
	 * Get the 项目信息表.
	 * 
	 * @return 项目信息表
	 */
	public ProjectInfo getPrjProjectInfo() {
		return this.prjProjectInfo;
	}

	/**
	 * Set the 专家确认表.
	 * 
	 * @param expertExpertConfirm
	 *            专家确认表
	 */
	public void setExpertExpertConfirm(ExpertConfirm expertExpertConfirm) {
		this.expertExpertConfirm = expertExpertConfirm;
	}

	/**
	 * Get the 专家确认表.
	 * 
	 * @return 专家确认表
	 */
	public ExpertConfirm getExpertExpertConfirm() {
		return this.expertExpertConfirm;
	}

	/**
	 * Set the 第几次抽取.
	 * 
	 * @param fetchTime
	 *            第几次抽取
	 */
	public void setFetchTime(Integer fetchTime) {
		this.fetchTime = fetchTime;
	}

	/**
	 * Get the 第几次抽取.
	 * 
	 * @return 第几次抽取
	 */
	public Integer getFetchTime() {
		return this.fetchTime;
	}

	/**
	 * Set the 抽取有效标志.
	 * 
	 * @param fetchStatus
	 *            抽取有效标志
	 */
	public void setFetchStatus(String fetchStatus) {
		this.fetchStatus = fetchStatus;
	}

	/**
	 * Get the 抽取有效标志.
	 * 
	 * @return 抽取有效标志
	 */
	public String getFetchStatus() {
		return this.fetchStatus;
	}

	/**
	 * Set the 执行评审开始时间.
	 * 
	 * @param reviewBegin
	 *            执行评审开始时间
	 */
	public void setReviewBegin(Date reviewBegin) {
		this.reviewBegin = reviewBegin;
	}

	/**
	 * Get the 执行评审开始时间.
	 * 
	 * @return 执行评审开始时间
	 */
	@Temporal(TemporalType.DATE)
	@JsonFormat(pattern = "yyyy-MM-dd")
	public Date getReviewBegin() {
		return this.reviewBegin;
	}

	/**
	 * Set the 执行评审结束时间.
	 * 
	 * @param reviewEnd
	 *            执行评审结束时间
	 */
	public void setReviewEnd(Date reviewEnd) {
		this.reviewEnd = reviewEnd;
	}

	/**
	 * Get the 执行评审结束时间.
	 * 
	 * @return 执行评审结束时间
	 */
	@Temporal(TemporalType.DATE)
	@JsonFormat(pattern = "yyyy-MM-dd")
	public Date getReviewEnd() {
		return this.reviewEnd;
	}

	/**
	 * Set the 专家接受任务标志。.
	 * 
	 * @param expertAccept
	 *            专家接受任务标志。
	 */
	public void setExpertAccept(String expertAccept) {
		this.expertAccept = expertAccept;
	}

	/**
	 * Get the 专家接受任务标志。.
	 * 
	 * @return 专家接受任务标志。
	 */
	public String getExpertAccept() {
		return this.expertAccept;
	}

	/**
	 * Set the 创建者.
	 * 
	 * @param createBy
	 *            创建者
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * Get the 创建者.
	 * 
	 * @return 创建者
	 */
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createDate
	 *            创建时间
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * Set the 更新者.
	 * 
	 * @param updateBy
	 *            更新者
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * Get the 更新者.
	 * 
	 * @return 更新者
	 */
	public String getUpdateBy() {
		return this.updateBy;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param updateDate
	 *            更新时间
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * Set the 备注信息.
	 * 
	 * @param remarks
	 *            备注信息
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the 备注信息.
	 * 
	 * @return 备注信息
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the 删除标记.
	 * 
	 * @param delFlag
	 *            删除标记
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the 删除标记.
	 * 
	 * @return 删除标记
	 */
	public String getDelFlag() {
		return this.delFlag;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((prjProjectInfo == null) ? 0 : prjProjectInfo.hashCode());
		result = prime * result + ((expertExpertConfirm == null) ? 0 : expertExpertConfirm.hashCode());
		result = prime * result + ((fetchTime == null) ? 0 : fetchTime.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ProjectExpert other = (ProjectExpert) obj;
		if (prjProjectInfo == null) {
			if (other.prjProjectInfo != null) {
				return false;
			}
		} else if (!prjProjectInfo.equals(other.prjProjectInfo)) {
			return false;
		}
		if (expertExpertConfirm == null) {
			if (other.expertExpertConfirm != null) {
				return false;
			}
		} else if (!expertExpertConfirm.equals(other.expertExpertConfirm)) {
			return false;
		}
		if (fetchTime == null) {
			if (other.fetchTime != null) {
				return false;
			}
		} else if (!fetchTime.equals(other.fetchTime)) {
			return false;
		}
		return true;
	}

}
